//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agency
    {
        public agency()
        {
            this.agency_metrics_categories = new HashSet<agency_metrics_categories>();
            this.client_dispositions = new HashSet<client_dispositions>();
            this.collections = new HashSet<collection>();
            this.domains = new HashSet<domain>();
            this.events = new HashSet<@event>();
            this.agency_people = new HashSet<agency_people>();
            this.mailers = new HashSet<mailer>();
            this.media = new HashSet<medium>();
            this.page_settings = new HashSet<page_settings>();
            this.pages = new HashSet<page>();
            this.rate_types = new HashSet<rate_types>();
            this.testimonials = new HashSet<testimonial>();
            this.agency_people_roles = new HashSet<agency_people_roles>();
        }
    
        public int agency_pk { get; set; }
        public string agency_name { get; set; }
        public string agency_url { get; set; }
        public int agency_level { get; set; }
        public string agency_googleanalytics { get; set; }
        public string agency_footer { get; set; }
        public string agency_css { get; set; }
        public Nullable<int> agency_skin_talent_public { get; set; }
        public Nullable<int> agency_skin_talent_private { get; set; }
        public Nullable<int> agency_skin_compsheet { get; set; }
        public string agency_social_facebook { get; set; }
        public string agency_social_twitter { get; set; }
        public string agency_social_linkedin { get; set; }
        public string agency_social_gplus { get; set; }
        public string agency_social_youtube { get; set; }
        public string agency_home_title { get; set; }
        public string agency_home_text { get; set; }
        public string agency_home_youtube { get; set; }
        public bool agency_has_logo { get; set; }
        public bool agency_has_favicon { get; set; }
        public string agency_address { get; set; }
        public string agency_city { get; set; }
        public string agency_zipcode { get; set; }
        public string agency_state { get; set; }
        public string agency_phone { get; set; }
        public string agency_email { get; set; }
        public string agency_taxid { get; set; }
        public bool agency_approved { get; set; }
        public string agency_join_firstname { get; set; }
        public string agency_join_lastname { get; set; }
        public string agency_join_email { get; set; }
        public int agency_talentapply_photoreq { get; set; }
        public string agency_talentapply_photo1 { get; set; }
        public string agency_talentapply_photo2 { get; set; }
        public string agency_talentapply_photo3 { get; set; }
        public string agency_talentapply_photo4 { get; set; }
        public string agency_talentapply_photo5 { get; set; }
        public string agency_mail_welcomeapplicant { get; set; }
        public string agency_location_name { get; set; }
        public string agency_location_url { get; set; }
        public Nullable<decimal> agency_location_lat { get; set; }
        public Nullable<decimal> agency_location_long { get; set; }
        public byte agency_display_nameformat { get; set; }
        public string agency_template_event { get; set; }
        public string agency_template_slot_public { get; set; }
        public string agency_template_slot_client { get; set; }
        public string agency_template_slot_talent { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<agency_metrics_categories> agency_metrics_categories { get; set; }
        public virtual ICollection<client_dispositions> client_dispositions { get; set; }
        public virtual ICollection<collection> collections { get; set; }
        public virtual ICollection<domain> domains { get; set; }
        public virtual ICollection<@event> events { get; set; }
        public virtual ICollection<agency_people> agency_people { get; set; }
        public virtual ICollection<mailer> mailers { get; set; }
        public virtual ICollection<medium> media { get; set; }
        public virtual ICollection<page_settings> page_settings { get; set; }
        public virtual ICollection<page> pages { get; set; }
        public virtual ICollection<rate_types> rate_types { get; set; }
        public virtual ICollection<testimonial> testimonials { get; set; }
        public virtual ICollection<agency_people_roles> agency_people_roles { get; set; }
    }
}
