//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agency_applicants
    {
        public int applicant_pk { get; set; }
        public int applicant_people_fk { get; set; }
        public int applicant_agency_fk { get; set; }
        public Nullable<int> applicant_slot_fk { get; set; }
        public Nullable<System.DateTime> applicant_approved { get; set; }
        public Nullable<System.DateTime> applicant_denied { get; set; }
        public Nullable<int> applicant_managedby_fk { get; set; }
        public bool applicant_is_spam { get; set; }
        public System.DateTime applicant_created { get; set; }
    }
}
