//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agency_people
    {
        public agency_people()
        {
            this.agency_people_rates = new HashSet<agency_people_rates>();
            this.flags = new HashSet<flag>();
        }
    
        public int agencypeople_pk { get; set; }
        public Nullable<int> agencypeople_agency_fk { get; set; }
        public int agencypeople_people_fk { get; set; }
        public Nullable<int> agencypeople_client_fk { get; set; }
        public System.Guid agencypeople_unique { get; set; }
        public string agencypeople_stagename { get; set; }
        public string agencypeople_displayname { get; set; }
        public string agencypeople_notes { get; set; }
        public string agencypeople_title { get; set; }
        public string agencypeople_biography { get; set; }
        public string agencypeople_experience { get; set; }
        public Nullable<int> agencypeople_todo_bitmask { get; set; }
        public Nullable<System.DateTime> agencypeople_created { get; set; }
        public bool agencypeople_is_exclusive { get; set; }
        public Nullable<int> agencypeople_applicant_eventslot_fk { get; set; }
    
        public virtual agency agency { get; set; }
        public virtual ICollection<agency_people_rates> agency_people_rates { get; set; }
        public virtual client client { get; set; }
        public virtual person person { get; set; }
        public virtual ICollection<flag> flags { get; set; }
    }
}
