//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agency_people_rates
    {
        public int peoplerate_ratetype_fk { get; set; }
        public int peoplerate_agencypeople_fk { get; set; }
        public int peoplerate_pk { get; set; }
        public decimal peoplerate_amount { get; set; }
    
        public virtual agency_people agency_people { get; set; }
        public virtual rate_types rate_types { get; set; }
    }
}
