//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agency_people_roles
    {
        public int agency_people_role_pk { get; set; }
        public Nullable<int> agency_pk { get; set; }
        public int people_pk { get; set; }
        public int role_pk { get; set; }
    
        public virtual agency agency { get; set; }
        public virtual person person { get; set; }
        public virtual role role { get; set; }
    }
}
