//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class collectiontalent
    {
        public int collectiontalent_collection_fk { get; set; }
        public int collectiontalent_talent_fk { get; set; }
        public int collectiontalent_addedby_fk { get; set; }
        public System.DateTime collectiontalent_added { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual person person { get; set; }
    }
}
