//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public collection()
        {
            this.collectiontalents = new HashSet<collectiontalent>();
        }
    
        public int collection_pk { get; set; }
        public Nullable<int> collection_agency_fk { get; set; }
        public int collection_people_fk { get; set; }
        public Nullable<int> collection_client_fk { get; set; }
        public bool collection_is_official { get; set; }
        public bool collection_is_orgshared { get; set; }
        public string collection_name { get; set; }
        public System.Guid collection_unique { get; set; }
        public bool collection_is_smart { get; set; }
    
        public virtual agency agency { get; set; }
        public virtual client client { get; set; }
        public virtual ICollection<collectiontalent> collectiontalents { get; set; }
    }
}
