//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        public string contract_pk { get; set; }
        public Nullable<int> contract_agency_fk { get; set; }
        public int contract_people_fk { get; set; }
        public Nullable<int> contract_event_fk { get; set; }
        public Nullable<System.DateTime> contract_signed { get; set; }
        public Nullable<System.DateTime> contract_ended { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual person person { get; set; }
    }
}
