//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_statuses
    {
        public event_statuses()
        {
            this.events = new HashSet<@event>();
        }
    
        public byte eventstatus_pk { get; set; }
        public string eventstatus_name { get; set; }
    
        public virtual ICollection<@event> events { get; set; }
    }
}
