//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public @event()
        {
            this.contracts = new HashSet<contract>();
            this.event_dates = new HashSet<event_dates>();
            this.event_people = new HashSet<event_people>();
            this.event_slots = new HashSet<event_slots>();
        }
    
        public int event_pk { get; set; }
        public int event_agency_fk { get; set; }
        public Nullable<int> event_client_fk { get; set; }
        public byte event_status_fk { get; set; }
        public bool event_status_forced { get; set; }
        public string event_title { get; set; }
        public string event_description { get; set; }
        public string event_summary { get; set; }
        public string event_website { get; set; }
        public string event_datetime_extrainfo { get; set; }
        public Nullable<int> event_category1_fk { get; set; }
        public Nullable<int> event_category2_fk { get; set; }
        public Nullable<int> event_category3_fk { get; set; }
        public string event_location_name { get; set; }
        public string event_location_address { get; set; }
        public string event_location_city { get; set; }
        public string event_location_state { get; set; }
        public string event_location_zip { get; set; }
        public Nullable<double> event_location_latitude { get; set; }
        public Nullable<double> event_location_longitude { get; set; }
        public Nullable<System.DateTime> event_approved { get; set; }
        public Nullable<int> event_approvedby_fk { get; set; }
        public Nullable<System.DateTime> event_archived { get; set; }
        public Nullable<int> event_archivedby_fk { get; set; }
        public System.Guid event_unique { get; set; }
        public bool event_allow_freelancers { get; set; }
        public Nullable<System.DateTime> event_startdate { get; set; }
        public Nullable<System.DateTime> event_enddate { get; set; }
    
        public virtual agency agency { get; set; }
        public virtual client client { get; set; }
        public virtual ICollection<contract> contracts { get; set; }
        public virtual ICollection<event_dates> event_dates { get; set; }
        public virtual ICollection<event_people> event_people { get; set; }
        public virtual ICollection<event_slots> event_slots { get; set; }
        public virtual event_statuses event_statuses { get; set; }
    }
}
