//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int log_pk { get; set; }
        public System.DateTime log_date { get; set; }
        public string log_text { get; set; }
        public int log_loginid { get; set; }
    }
}
