//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mailer
    {
        public long mailer_pk { get; set; }
        public string mailer_emailaddress { get; set; }
        public string mailer_subject { get; set; }
        public string mailer_template { get; set; }
        public string mailer_json { get; set; }
        public System.DateTime mailer_sendafter { get; set; }
        public Nullable<System.DateTime> mailer_senton { get; set; }
        public Nullable<int> mailer_agency_fk { get; set; }
        public Nullable<System.Guid> mailer_source { get; set; }
        public Nullable<int> mailer_key { get; set; }
        public System.Guid mailer_unsubscribetype { get; set; }
        public System.Guid mailer_unsubscribeall { get; set; }
    
        public virtual agency agency { get; set; }
    }
}
