//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class metrics_custom
    {
        public int metricscustom_people_fk { get; set; }
        public int metricscustom_pk { get; set; }
        public string metricscustom_title { get; set; }
        public bool metricscustom_is_featured { get; set; }
    
        public virtual person person { get; set; }
    }
}
