//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class metrics_categories
    {
        public metrics_categories()
        {
            this.agency_metrics_categories = new HashSet<agency_metrics_categories>();
            this.metrics = new HashSet<metric>();
        }
    
        public int metriccategory_pk { get; set; }
        public int metriccategory_parent_fk { get; set; }
        public string metriccategory_title { get; set; }
        public bool metriccategory_is_multiple { get; set; }
        public bool metriccategory_is_eventcat { get; set; }
        public Nullable<int> metriccategory_ordinal { get; set; }
        public bool metriccategory_contains_categories { get; set; }
        public string metriccategory_lineage { get; set; }
        public bool metriccategory_calculated { get; set; }
        public string metriccategory_fulltitle { get; set; }
    
        public virtual ICollection<agency_metrics_categories> agency_metrics_categories { get; set; }
        public virtual ICollection<metric> metrics { get; set; }
    }
}
