//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public int note_pk { get; set; }
        public int note_creator_fk { get; set; }
        public bool note_is_private { get; set; }
        public Nullable<int> note_agency_fk { get; set; }
        public string note_text { get; set; }
        public Nullable<int> note_client_fk { get; set; }
        public Nullable<int> note_talent_fk { get; set; }
        public Nullable<int> note_event_fk { get; set; }
    
        public virtual person person { get; set; }
    }
}
