//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_pk { get; set; }
        public Nullable<int> payment_from { get; set; }
        public Nullable<int> payment_to { get; set; }
        public string payment_description { get; set; }
        public Nullable<byte> payment_method { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public System.DateTime payment_created { get; set; }
        public int payment_createdby_fk { get; set; }
    }
}
