//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class people_metrics
    {
        public int peoplemetrics_people_fk { get; set; }
        public int peoplemetrics_metric_fk { get; set; }
        public System.DateTime peoplemetrics_created { get; set; }
        public bool peoplemetrics_is_featured { get; set; }
        public int peoplemetrics_pk { get; set; }
        public Nullable<int> peoplemetrics_agency_fk { get; set; }
    
        public virtual person person { get; set; }
    }
}
