//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class people_locations
    {
        public int peoplelocation_pk { get; set; }
        public int peoplelocation_people_fk { get; set; }
        public string peoplelocation_verbose { get; set; }
        public double peoplelocation_lat { get; set; }
        public double peoplelocation_long { get; set; }
        public bool peoplelocation_is_primary { get; set; }
    
        public virtual person person { get; set; }
    }
}
