//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class private_notes
    {
        public int privatenotes_pk { get; set; }
        public int privatenotes_people_fk { get; set; }
        public int privatenotes_user_fk { get; set; }
        public string privatenotes_text { get; set; }
        public bool privatenotes_is_shared { get; set; }
        public System.DateTime privatenotes_created { get; set; }
    
        public virtual person person { get; set; }
    }
}
