//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate_types
    {
        public rate_types()
        {
            this.agency_people_rates = new HashSet<agency_people_rates>();
        }
    
        public int ratetype_pk { get; set; }
        public string ratetype_name { get; set; }
        public int ratetype_agency_fk { get; set; }
    
        public virtual agency agency { get; set; }
        public virtual ICollection<agency_people_rates> agency_people_rates { get; set; }
    }
}
