//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.agency_people_roles = new HashSet<agency_people_roles>();
        }
    
        public int RoleId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<agency_people_roles> agency_people_roles { get; set; }
    }
}
