//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag
    {
        public int tag_pk { get; set; }
        public int tag_agency_fk { get; set; }
        public string tag_name { get; set; }
        public int tag_used { get; set; }
    
        public virtual tag_usage tag_usage { get; set; }
    }
}
