//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyAlchemy.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag_usage
    {
        public int tagusage_tag_fk { get; set; }
        public Nullable<int> tagusage_event_fk { get; set; }
        public Nullable<int> tagusage_talent_fk { get; set; }
        public Nullable<int> tagusage_client_fk { get; set; }
    
        public virtual tag tag { get; set; }
    }
}
